### ISSUE TITLE
Publish for R-v4.1

### ISSUE THREAD

**Issue by abhi18av** [ParkerICI/datalogr#12]
Hi team,

Thanks for the wondeful library - I'm really looking forward to trying this out!

However, with `R v4.1.1` , I see the following error while trying to install `datalogr`

```

> install.packages("datalogr")
Warning in install.packages :
  package ‘datalogr’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

Are there any plans to support this version soon?

**Comment by timhowes** [comment]
The package isn't published on CRAN, but can be installed from Github using the `devtools` package. To install, run `devtools::install_github("ParkerICI/datalogr")`.

**Comment by abhi18av** [comment]
Ah, I see. Beginner mistake 😅 

I'm looking forward to trying out this package with Use with datalevin https://github.com/juji-io/datalevin, if possible.
